services:
  python:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - ./simple-app.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
      - ~/.ssh:/home/vscode/.ssh:ro
    depends_on:
      - db
      - redis
  db:
    image: postgres:17-bullseye
    restart: always
    shm_size: 2gb
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hello_db
    expose:
      - 5432
  redis:
    image: redis:alpine
    expose:
      - 6379
  caddy:
    image: caddy:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - python
      - mailhog
  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025

volumes:
  caddy_data:
  postgres:
